titles:
  about: Обо мне
  contact: Контакты
  skills: Навыки
  stack: Стэк
  education: Образование
  exp: Опыт работы
  activities: Активности
  diploma: ВКР

basic:
  firstname: Матвей
  lastname: Гаврилов
  position: Инженер-программист
  email: matveigavrilov@mail.ru
  tg: matveigavrilov1
  phone: +7 (999) 526-40-52
  github: matveigavrilov1

education:
  - degree: Бакалавр
    title: Информационные системы и технологии
    institution: Санкт-Петербургский государственный электротехнический университет ЛЭТИ имени В.И. Ульянова Ленина
    date: "2025"
    diploma: Решение задачи синхронизации доступа к разделяемым данным при исполнении сопрограмм в многопточных информационных системах
