titles:
  about: Обо мне
  contact: Контакты
  skills: Навыки
  stack: Стэк
  education: Образование
  exp: Опыт работы
  activities: Активности
  diploma: ВКР

basic:
  firstname: Матвей
  lastname: Гаврилов
  position: Инженер-программист
  email: matveigavrilov@mail.ru
  tg: matveigavrilov1
  phone: +7 (999) 526-40-52
  github: matveigavrilov1

education:
  - degree: Бакалавр
    title: Информационные системы и технологии
    institution: Санкт-Петербургский государственный электротехнический университет ЛЭТИ имени В.И. Ульянова Ленина
    date: "2025"
    diploma: Решение задачи синхронизации доступа к разделяемым данным при исполнении сопрограмм в многопточных информационных системах

exp:
  - company: YADRO
    date:
      start: "Ноябрь 2024"
      end: "н.в."
    position: Младжий инженер-программист
    achievments:
    - "Разработал систему шифрования пакетов ПО, их поставки и последующей расшифровки с валидацией и инсталляцией на базовую станцию для сетей LTE/GSM"
    - "Разработал систему для обеспечения установки ПО по NetBoot для GSM контроллера"
    - "Портировал процедуру обновления ПО с базовой станции на GSM контроллер с глобальной переработкой стиля написания кода на языке Bash"
    - "Изучил руководства по эксплуатации RAID-контроллера и настроил RAID-5 с использованием самошифрующихся дисков на тестовом стенде GSM-контроллера"
    - "Выступал в роли куратора для новых сотрудников, а также для стажеров программы Импульс"
    stack: C++20, Bash, Python, Bazel, gtest, doit, poetry, Yocto, sysrepo, systemd, openssl, Gitlab, Bitbucket, Jira
  - company: НТЦ "Протей"
    date:
      start: "Январь 2024"
      end: "Ноябрь 2024"
    position: Младжий инженер
    achievments:
    - "Разработал и интегрировал систему контроля работоспособности приложения MME пакетного ядра мобильной сети"
    - "Переработал на JSON-формат систему конфигурирования приложения MME для взаимодействия Web-интерфейсом"
    - "Разработал и интегрировал с CI конвертер для преобразования старых конфигураций приложения MME в новые"
    - "Переработал конфигурации сборки CMake приложения MME для более гибкой интеграции с CI и командой тестирования"
    stack: C++11-17, Python, Bash, CMake, gtest, Jenkins, Gitlab, YouTrack