titles:
  summary: Резюме
  contact: Контакты
  skills: Навыки
  stack: Стэк
  education: Образование
  exp: Опыт работы
  activities: Активности
  diploma: ВКР
  soft: Soft скиллы
  languages: Языки программирования
  db: Базы данных
  devtools: Инструменты разработчика
  cicd: CI/CD
  frameworks: Фреймворки
  other: Дополнительно

basic:
  firstname: Матвей
  lastname: Гаврилов
  position: Инженер-программист
  age: "22 года"
  city: Москва, Россия

summary: C++ разработчик с 2-летним опытом работы в Телеком-направлении. Интересуюсь линуксом и компьютерными сетями.

contact:
  email: matveigavrilov@mail.ru
  tg: matveigavrilov1
  phone: +7 (999) 526-40-52
  github: matveigavrilov1

skills:
  languages:
   - C++20
   - Bash
   - Python3
  db:
   - PostgreSQL
   - sysrepo
  devtools:
   - git
   - CMake
   - Bazel
   - conan
   - poetry
   - doit
  cicd:
   - Docker
   - Jenkins
  frameworks:
   - Boost
   - gtest
  other:
   - Компьютерные сети
  
education:
  - degree: Бакалавр
    title: Информационные системы и технологии
    institution: Санкт-Петербургский государственный электротехнический университет ЛЭТИ имени В.И. Ульянова Ленина
    date: "2025"
    diploma: Решение задачи синхронизации доступа к разделяемым данным при исполнении сопрограмм в многопоточных информационных системах

exp:
  - company: YADRO
    date:
      start: "Ноябрь 2024"
      end: "н.в."
    position: Младжий инженер-программист
    summary: "Работал в команде разработки платформы, обеспечивающей инфраструктуру для работы продуктовых сервисов базовой станции для сетей LTE/GSM, а также GSM-контроллера"
    achievments:
    - "Разработал систему шифрования пакетов ПО, их поставки и последующей расшифровки с валидацией и инсталляцией на базовую станцию для сетей LTE/GSM"
    - "Разработал систему для обеспечения установки ПО по NetBoot для GSM контроллера"
    - "Портировал процедуру обновления ПО с базовой станции на GSM контроллер с глобальной переработкой стиля написания кода на языке Bash"
    - "Изучил руководства по эксплуатации RAID-контроллера и настроил RAID-5 с использованием самошифрующихся дисков на тестовом стенде GSM-контроллера"
    - "Выступал в роли куратора для новых сотрудников, а также для стажеров программы Импульсп"
    stack: C++20, Bash, Python, Bazel, Conan, doit, poetry, Docker, Yocto, sysrepo, systemd, openssl, Gitlab, Bitbucket, Jira
  - company: НТЦ "Протей"
    date:
      start: "Январь 2024"
      end: "Ноябрь 2024"
    position: Младжий инженер
    summary: "Работал в команде разработки приложением MME для пакетного ядра сетей LTE"
    achievments:
    - "Разработал и интегрировал систему контроля работоспособности приложения MME"
    - "Переработал на JSON-формат систему конфигурирования приложения MME для взаимодействия Web-интерфейсом"
    - "Разработал и интегрировал с CI конвертер для преобразования старых конфигураций приложения MME в новые"
    - "Переработал конфигурации сборки CMake приложения MME для более гибкой интеграции с CI и командой тестирования"
    stack: C++11-17, Python, Bash, CMake, Docker, gtest, Jenkins, Gitlab, YouTrack

activities:
  - title: "Решение задачи синхронизации при исполнении корутин C++20 в многопоточной среде"
    date: "Весна 2025"
    description: "В рамках работы над ВКР разработал архитектуру многопоточного исполнения корутин, а также универсальный метод их синхронизации. Для обоснования ценности разработал программу бенчмарк, в рамках анализа работы которой был выявлен 30-процентный прирост производительности по сравнению с классическими методами синхронизации."
  - title: "IT-ЛЭТИ. Семинар по корутинам"
    date: "Май 2025"
    description: "Разработал программу семинара по погружению в устройство корутин C++20 для студентов кафедры IT-ЛЭТИ"
  - title: "termKeeper"
    date: "Февраль 2025"
    description: "Разработал приложение для хранения и получения быстрого доступа к часто используемым сложным терминальным командам. Для реализации был разработан собственный движок для отображения пользовательского интерфейса в консоли"
  - title: "IT-ЛЭТИ. Курс по языку C++ "
    date: "2024"
    description: "Разработал и в течение учебного семестра вел образовательный курс по C++ и STL для студентов кафедры IT-ЛЭТИ. Ссылка: https://github.com/matveigavrilov1/IT-LETI-2024-CXX-STL"